parameters:
- name: environment
  type: string
- name: azureServiceConnection
  type: string
- name: location
  type: string
- name: solutionName
  type: string

stages:
- stage: deploy
  displayName: 'Deploy to ${{ parameters.environment }}'
  jobs:
  - deployment: deploy_arm
    displayName: 'Deploy ARM to ${{ parameters.environment }}'
    condition: succeeded()
    pool:
      vmImage: 'Ubuntu-20.04'
    variables:
      azPowershellVersion: 5.5.0
    environment: ${{ parameters.environment }}
    strategy:
      runOnce:
        deploy:
          steps:
          - checkout: self
          - template: step.install-gitversion.yml
            parameters:
              gitversionConfigFile: $(Build.SourcesDirectory)/infrastructure-as-code/GitVersion.yml
          - task: AzurePowerShell@4
            displayName: 'Deploy ARM'
            inputs:
              azureSubscription: ${{ parameters.azureServiceConnection }}
              scriptType: filePath
              scriptPath: infrastructure-as-code/scripts/Deploy.ps1
              scriptArguments: >
                -Environment ${{ parameters.environment }}
                -Version $(GitVersion.SemVer)
                -Location "${{ parameters.location }}"
                -SolutionName "${{ parameters.solutionName }}"
                -DeploymentOutputFile "armOutput.json"
              azurePowerShellVersion: 'OtherVersion'
              preferredAzurePowerShellVersion: $(azPowershellVersion)

          - task: PowerShell@2
            displayName: 'Publish Outputs'
            inputs:
              filePath: infrastructure-as-code/scripts/PublishOutputs.ps1
              arguments: >
                -AzureDevOpsPAT "$(System.AccessToken)"
                -AzureDevOpsOrganization $(System.TeamFoundationCollectionUri)
                -AzureDevOpsProject "$(System.TeamProject)"
                -GroupName "mlops-iac-cd-output-${{ parameters.environment }}"
                -DeploymentOutputFile "armOutput.json"
              pwsh: true
              showWarnings: true
            env:
              AzureDevOpsPAT: $(System.AccessToken)