model:
    name: 'hate-pt-speech'
    baseline: 'neuralmind/bert-base-portuguese-cased'
    output_dir: './outputs'
trainer:
    output_dir: './outputs/results'
    logging_dir: './outputs/board'
    num_train_epochs: 3
    per_device_train_batch_size: 64
    per_device_eval_batch_size: 64
    learning_rate: 0.00005
    warmup_steps: 500
    weight_decay: 0.01
    report_to: 
     - "tensorboard"
data:
    format: 'csv'
    preprocessing:
        split_unique_words: 150
        split_seq_len: 200
