trigger: none

pool:
  vmImage: ubuntu-latest

variables:
  - template: variables.group.yaml

stages:
- stage: aml_ensure_env
  displayName: Environments - Integration
  jobs:
  - job: integrate
    displayName: Environments - Integration
    steps:
      - template: templates/aml-cli-install/step.yaml
        parameters:
          componentSupport: false
          minVersion: 2.0

      - template: templates/conda-setup/step.yaml

      - template: templates/aml-env-build/step.yaml
        parameters:
          envFile: .aml/environments/*/environment.yml

      - template: templates/aml-env-ensure/step.yaml
        parameters:
          azureServiceConnectionName: $(SERVICECONNECTION)
          envFile: .aml/environments/*/environment.yml
          validateOnly: true
          failOnMissing: false
          workspaceName: $(WORKSPACENAME)
          resourceGroup: $(RESOURCEGROUPNAME)
