parameters:
- name: azureServiceConnectionName
  type: string
- name: datasetFile
  type: string
- name: workspaceName
  type: string
- name: resourceGroup
  type: string
- name: initialize
  type: boolean
  default: false
- name: initialDataPath
  type: string
  default: data
- name: storageAccount
  type: string
  default:

steps:
  - task: AzureCLI@2
    name: datasetsInit
    displayName: Generating datasets
    inputs:
      scriptType: bash
      scriptLocation: scriptPath
      azureSubscription: ${{ parameters.azureServiceConnectionName }}
      scriptPath: $(Build.SourcesDirectory)/.azure-pipelines/templates/aml-dataset-create/step.sh
      arguments: ${{ parameters.datasetFile }} ${{ parameters.workspaceName }} ${{ parameters.resourceGroup }} ${{ lower(parameters.initialize) }} ${{ parameters.initialDataPath }} ${{ parameters.storageAccount }}
